### ISSUE TITLE
Provising ble issue

### ISSUE THREAD

**Issue by suryasid09** [listout/provisoning_nimble#1]
Hello,

I saw your comment regarding deinitialization of nimble stack. I am also facing almost the same issue. 

    if(bit1 && bit2)
    {
    	nimble_port_stop();
    	nimble_port_deinit();
    	configure_sta_mode();
    }

The problem is configure_sta_mode() is never called. And the Program stuck after that. 

were you able to solve the issue? I would appreciate help in this regard.
![nimble](https://github.com/listout/provisoning_nimble/assets/119737596/acf3c5e7-9ffd-4802-8408-71a1a1fd31d4)

**Comment by listout** [comment]
I don't know which ESP-IDF version you are using, but I'm on the master branch. As you can see from the below screenshot I can connect fine with the WiFi creds. given from the ESP provisioning app. I also couldn't find the `configure_sta_mode` function, is that a custom one?


![image](https://github.com/listout/provisoning_nimble/assets/66715002/6810a833-03ec-4c2d-a727-b1394317d052)

**Comment by suryasid09** [comment]
I have solved the issue. As you pointed out, I was using different version and not master branch but thanks to you I have changed it and now its working.

**Comment by listout** [comment]
Great!
